title: Ayaan Saif
#logo: 
description: |
  Hello! My name is Ayaan Saif. The prospect of leaving a positive impact on people's lives through the applications I build is what gets me out of bed every morning.

  I'm a keen project manager and team player, and I strive to be the catalyst for success in every project I'm involved in. 

theme: jekyll-theme-minimal
